### ISSUE TITLE
Kubernetes role more abstracted

### ISSUE THREAD

**Issue by zmmdv** [caermeglaeddyv/ansible-roles#3]
Hello @caermeglaeddyv . Can you please make your role abstracted. Like your role setups the latest possible k8s version and all components. Something like just change your hosts file with your ips add ssh key and start the roles. And put the variables inside if someone will need specific versions of k8s or docker or haproxy etc. Thank you very much, hope you doing well

**Comment by caermeglaeddyv** [comment]
Hi, @zmmdv !
Thank you for trying out roles.
In future, please open issues in corresponding role's repository.
About an issue, I think you meant support for additional software versions of kubernetes and etc., not the abstraction, because I believe that I made roles as much abstract as I can for now. As you see, the main idea of this roles is to provide wide variety of options to deploy infrastructure of cloud-native technologies on-premise. As a result, complexity grows and it is hard to provide support of all possible software versions at once.
About hosts and ssh keys, I believe that there is always an option to provide your own inventory and ssh keys in roles, please read comments carefully and tell if you need further help, I can provide you links and instructions if there are not enough in README files.
About variables, again, I believe I've been provided default variables in most roles, please check them out in defaults/main.yml file.
If I understood something wrong, please feel free to correct me and provide details, will answer ASAP, also feel free with contribution to documentation or code with pull requests, I promise that will review every one of them. 
Again, that's a lot for attention.
